data_kwargs:
  dataset: multilingual
  
  build_vocab_kwargs:
    src_min_freq: 2
    trg_min_freq: 2
    # src_max_size: 8000
    # trg_max_size: 8000
    src_specials: 
      - <pad>
      - <unk>
    trg_specials:
      - <pad>
      - <unk>
      - <eos>
      - <en>
      - <vi>


model: transformer_nmt
model_kwargs:
  # Architecture config
  d_model: 512
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_ff: 2048
  dropout: 0.1
  activation: relu
  max_input_length: 200
  

# Config for training
train_config:
  lazy: false
  cache_lines: 1e6

  train_ds_kwargs:
    en_vi:
      src_lang: en
      trg_lang: vi
      src_path: ../data/iwslt_en_vi/train.en
      trg_path: ../data/iwslt_en_vi/train.vi 
      src_max_len: 64
      trg_max_len: 64
    # vi_en:
    #   src_lang: vi
    #   trg_lang: en
    #   src_path: ../data/iwslt_en_vi/train.vi
    #   trg_path: ../data/iwslt_en_vi/train.en 
    #   src_max_len: 64
    #   trg_max_len: 64

  valid_ds_kwargs:
    en_vi:
      src_lang: en
      trg_lang: vi
      src_path: ../data/iwslt_en_vi/tst2013.en
      trg_path: ../data/iwslt_en_vi/tst2013.vi
    # vi_en:
    #   src_path: ../data/iwslt_en_vi/tst2013.vi
    #   trg_path: ../data/iwslt_en_vi/tst2013.en

  train_batch_sz: 64
  valid_batch_sz: 64
  train_n_tokens: 8000
  valid_n_tokens: 8000

  optimizer: adam
  optimizer_kwargs:
    beta1: 0.9
    beta2: 0.98
    lr: 0.2
    eps: !!float 1e-9

  scheduler: noam
  scheduler_kwargs:
    scalar: 0.2
    warmup_steps: 4000
    d_model: 512
  
  loss_metric: label_smoothing_loss
  loss_kwargs:
    label_smoothing: 0.1

  n_epochs: 30
  report_steps: 200
  valid_epochs: 1
  eval_epochs: 1
  save_checkpoint_epochs: 1
  use_float32: true

  eval_metric: bleu
  strategy: beam_search
  strategy_kwargs:
    k: 4
    max_len: 160
    alpha: 0.6
    beta: 0.0
    support_kwargs:
      use_actives: false
      use_cache: true

infer_config:
  strategy: beam_search
  batch_size: 32
  n_tokens: 4096
  strategy_kwargs:
    k: 4
    max_len: 160
    alpha: 0.6
    beta: 0.0
    support_kwargs:
      use_actives: false
      use_cache: true

device: cuda
keep_checkpoints: 5
